theme: jekyll-theme-minimal
title: Kate Bayard
description: A creative, analytical, problem solver with a passion for providing high quality customer experiences. Pursuing a career in Software Development in order to build the tools that will help businesses serve their customers better as well as become more efficient and profitable. Former marketer with experience in online marketing, website development, and Salesforce administration.
logo: https://avatars1.githubusercontent.com/u/47252562?s=460&v=4
show_downloads: true
